# Generated by Django 3.2.12 on 2022-02-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='additional_documents_image',
            field=models.ImageField(blank=True, upload_to='images/documents/'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='pancard_image',
            field=models.ImageField(blank=True, upload_to='images/pancard/'),
        ),
    ]
