# Generated by Django 3.2.12 on 2022-02-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220227_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userall',
            name='account_verfication',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'VERIFIED'), (1, 'NOT VERIFIED'), (2, 'IN PROCESS'), (3, 'BLOCKED')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='userall',
            name='email_verfication',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'VERIFIED'), (1, 'NOT VERIFIED')], default=1, null=True),
        ),
    ]
