# Generated by Django 3.2.12 on 2022-02-27 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220227_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountfund',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userall'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userall'),
        ),
        migrations.AlterField(
            model_name='usermetadata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userall'),
        ),
    ]
